django/01. django_model/crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('delete/<pk>', views.delete, name='delete'),
    path('update/<pk>', views.update, name='update'),
    path('edit/<pk>', views.edit, name='edit'),
    path('detail/<pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('new/', views.new, name='new'),
    path('', views.index, name='index'),
]

django/01. django_model/crud/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

django/01. django_model/crud/articles/models.py
from django.db import models
from django.db.models.base import Model

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

django/01. django_model/crud/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def new(request):
    return render(request, 'articles/new.html')

def index(request):
    articles = Article.objects.all()
    
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html', context)

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:index')

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/detail.html', context)

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article.objects.get(pk=pk)
    article.title = title
    article.content = content
    article.save()
    return redirect('articles:detail', article.pk)

def delete(request, pk):
    if request.method == 'POST':
        article = Article.objects.get(pk=pk)
        article.delete()
    return redirect('articles:index')

django/01. django_model/crud/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}

  <h1>DETAIL</h1>
  <hr>
  <h2>{{ article.title }}</h2>
  <p>{{ article.content }}</p> 
  <p>작성일: {{ article.created_at }}</p>
  <p>수정일: {{ article.updated_at }}</p> 
  <a href="{% url 'articles:index' %}">BACK</a>
  <a href="{% url 'articles:edit' article.pk %}">EDIT</a>
  {% comment %} <a href="{% url 'articles:delete' article.pk %}">DELETE</a> {% endcomment %}
  <form action="{%url 'articles:delete' article.pk%}" method='POST'>
  {% csrf_token %}
  <button>DELETE</button>
  </form>

{% endblock  %}

django/01. django_model/crud/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}

  <h1>EDIT</h1>
  <form action="{% url 'articles:update' article.pk %}" method = 'POST'>
    {% csrf_token %}
    <label for="title">TITLE: </label>
    <input type="text" id="title" name="title" value="{{ article.title }}"><br>
    <label for="content">CONTENT: </label>
    <textarea name="content" cols="30" rows="10">{{ article.content }}</textarea><br>
    <input type="submit" value='수정'>
  </form>

  <a href="{% url 'articles:detail' article.pk %}">BACK</a>

{% endblock %}

django/01. django_model/crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}

  <h1>INDEX</h1>
  <a href= "{% url 'articles:new' %}">NEW</a>
  {% for article in articles %}
    <h2>제목: {{ article.title }}</h2>
    <a href= "{% url 'articles:detail' article.pk %}">DETAIL</a>
  {% empty %}
    <h2>아직 작성된 내용이 없습니다.</h2>
  {% endfor %}
  <hr> 


{% endblock %}

django/01. django_model/crud/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}

  <h1>NEW</h1>
  <form action="{% url 'articles:create' %}" method = 'POST'>
    {% csrf_token %}
    <label for="title">TITLE: </label>
    <input type="text" id="title" name="title"><br>
    <label for="content">CONTENT: </label>
    <textarea name="content" cols="30" rows="10"></textarea><br>
    <input type="submit" value='작성'>
  </form>

  <a href="{% url 'articles:index' %}">BACK</a>

{% endblock %}

django/01. django_model/crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

  {% block content %}
  {% endblock content %}
  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>